for index in {1..20}
do
  echo "AVAVAV\\AVAVA::VAV..VAVA::VAVAV//AVAV"
  echo "VAVAV//AVAVA::VAVAV..VAVA::VAV\\AVAVA"
  echo "VAVAVA\\VAVAV::AVAV..AVA::VAVAV//AVAV"
  echo "AVAVA//VAVAV::AVAV..AVAVA::VAV\\AVAVA"
done